[package]
name = "http_socks_bridge-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["server", "client", "http1", "tcp"] }
tokio-socks = "0.5"
log = "0.4"
env_logger = "0.9"
